services:
  gitverse-notifier:
    build:
      context: .
      args:
        VERSION: ${VERSION:-latest}
        COMMIT: ${COMMIT:-}
    image: gitverse-notifier:${VERSION:-latest}
    container_name: gitverse-notifier
    ports:
      - "${HTTPD_PORT:-9001}:80"
    volumes:
      - ./config.yml:/opt/gitverse_notifier/config.yml:ro
      - ./configs:/opt/gitverse_notifier/configs:ro
      - ./data:/opt/gitverse_notifier/data
    command: ["./gitverse_notifier", "-f", "/opt/gitverse_notifier/config.yml"]
    restart: unless-stopped
