repository: any

# Базовый URL gitverse для ссылок в уведомлениях.
# Пустое значение — берётся GITVERSE_BASE_URL из глобального конфига.
url: ""

# Разрешённые коды проектов Jira
# Пустой список — без ограничений.
allowed_jira_projects:
  - JIRA
  - TEST

telegram_tags:
  test: test

event_batches:
  - key: events_batch
    group_by: pull_request_batch
    strategy: use_last_event
    event: pull_request.review_requested
    size: 5
    timeout: 60

action_rules:
  - on: pull_request.opened
    action: jira.comment_issue
    template: jira/pr_opened

  - on: pull_request.opened
    action: telegram.notify
    template: telegram/pr_opened

  - on: pull_request.edited
    action: utils.log

  - on: pull_request.closed
    state: merged
    action: telegram/pr_merged

  - on: pull_request.closed
    state: closed
    action: utils.log

  - on: pull_request.synchronized
    action: utils.log

  - on: pull_request.review_requested
    action: telegram.notify
    template: telegram/review_requested

  - on: pull_request.review_approved
    action: telegram.notify
    template: telegram/review_approved

  - on: pull_request.comment
    action: telegram.notify
    skip_empty: true
    template: telegram/pr_comment

  - on: branch.push
    branch: main
    action: telegram.notify
    template: telegram/branch_push

  - on: branch.created
    action: jira.comment_issue
    template: jira/branch_created

  - on: branch.created
    action: telegram.notify
    template: telegram/branch_created

  - on: pull_request.edited
    action: utils.log

  - on: pull_request.closed
    action: utils.log

  - on: pull_request.synchronized
    action: utils.log

  - on: branch.deleted
    action: utils.log

  - on: pull_request.review_rejected
    action: utils.log

  - on: pull_request.review_comment
    action: utils.log

  - on: cicd.status
    action: utils.log
    cicd_context: rspec
    cicd_state: failure
