repository: any

actions:
  - on: pull_request.opened
    action: jira.comment_issue
    template: jira/pr_created

  - on: pull_request.review_requested
    action: telegram.notify

  - on: pull_request.review_approved
    action: telegram.notify

  - on: pull_request.comment
    action: telegram.notify
    template: jira/pr_new-comment

  - on: branch.push
    branch: main
    action: telegram.notify

  - on: branch.created
    action: telegram.notify
